### ISSUE TITLE
String Comparison - Case Sensitivity

### ISSUE THREAD

**Issue by triple-j** [donatj/XLS-XML-Formula-Expander#3]
Excel is case insensitive, XLS-XML-Formula-Expander is not.

"Bob" = "BOB" evaluates as TRUE in Excel, but XXLS returns FALSE.

**Comment by donatj** [comment]
You don't even work at ECW anymore, right? And it looks like the site this was built for isn't even run by ECW anymore.

**Comment by triple-j** [comment]
Correct, I haven't worked at ECW for a few years now.  I didn't even realize this issue was still open.

**Comment by donatj** [comment]
Haha, it's cool. How's it going?
